apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tic-tac-toe
spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: backend

          image: 755395261632.dkr.ecr.us-east-1.amazonaws.com/platform/tic-tac-toe/back-end:v3

          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8000

          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: DB_HOST
              value: postgres

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: APP_ENV
              value: prod

            - name: LOG_LEVEL
              value: INFO

          readinessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi